### ISSUE TITLE
Use restful route for posts#show path

### ISSUE THREAD

**Issue by nathanallen** [jevangelista/Vagabond_Project_Team2#4]
Change `/users/:title/posts` to `/posts/:title`. (You'd think it should be something like `/users/:id/posts/:title` but there's no need for the nesting in this case).

A nice touch would be `/posts/the-title-with-dashes` (but don't spend too much time on it).

**Comment by nathanallen** [comment]
In other words, I should be able to go to:

"/posts/10" and see the post with an id of 10. i.e. `posts/:id`

Or (since you're using the titles as a "slug"), I should be able to go to:

"/posts/The%20White%20Rose%20of%20Northern%20Ireland" and see the post with a title of "The White Rose of Northern Ireland". I.e. `posts/:title`

**Comment by nathanallen** [comment]
Here's the bug:

``` html
<%= link_to post.title, user_posts_path(post.title) %>
```

Running `rake routes` I see:

```
user_posts GET    /users/:id/posts(.:format) users#posts
```

This directs me to a scary looking url like:

"/users/The%20Mutant%20Who%20Fell%20to%20Earth/posts"

The correct path should be:

"/posts/The%20Mutant%20Who%20Fell%20to%20Earth" (`posts/:title`)

or

"/posts/10" (`posts/:id`)

**Comment by jevangelista** [comment]
Updated the route so it should now be posts/:title
